# path to the directory where images are located
# For Windows: it's like  D:\images\
filepath: images/
image_types: png,jpg

# sites 
host: https://ap-demo-core.labflow.ai/
upload_host: https://ap-demo-upload.labflow.ai/

# cat configs/core/cytomineconfig.groovy | grep adminPublicKey
admin_public_key: 36dfd7b7-d09f-4c93-9592-d19d9cf10ca6

# cat configs/core/cytomineconfig.groovy | grep adminPrivateKey
admin_private_key: da206cf1-5c01-41ed-994e-577de113d2a0

# Default is blank 
id_project: 

